# Extract a mechanical T1 card specification from decompiled Java sources.
# The constructor super(...) values are preferred over stale constant declarations.
# Usage: .\extract-sts1-spec.ps1 -JavaDir <cards> -OutFile <json>
[CmdletBinding()]
param([Parameter(Mandatory=$true)][string]$JavaDir,[Parameter(Mandatory=$true)][string]$OutFile)
$ErrorActionPreference='Stop';$utf8NoBom=New-Object System.Text.UTF8Encoding($false);if(-not(Test-Path -LiteralPath $JavaDir)){throw "Java source directory not found: $JavaDir"}
function Grab([string]$text,[string]$pattern){$m=[regex]::Match($text,$pattern);if($m.Success){return $m.Groups[1].Value};return $null}
function Resolve-Num([string]$token,[string]$text){if([string]::IsNullOrWhiteSpace($token)){return $null};if($token -match '^-?\d+$'){return [int]$token};$m=[regex]::Match($text,('\bint\s+'+[regex]::Escape($token)+'\s*=\s*(-?\d+)'));if($m.Success){return [int]$m.Groups[1].Value};return $null}
function Super-Cost([string]$text){$m=[regex]::Match($text,'super\(([^;]*)\)\s*;');if(-not$m.Success){return $null};$parts=$m.Groups[1].Value -split ',';if($parts.Count-lt 4){return $null};$tok=$parts[3].Trim();if($tok -match '^-?\d+$'){return [int]$tok};return $null}
$cards=@();foreach($f in(Get-ChildItem -LiteralPath $JavaDir -Recurse -File -Filter '*.java'|Sort-Object FullName)){$t=Get-Content -LiteralPath $f.FullName -Raw -Encoding UTF8;$id=Grab $t 'public static final String ID = "([^"]+)"';if(-not$id){$id=$f.BaseName};$cost=Super-Cost $t;$costSource='super';if($null-eq$cost){$cost=Resolve-Num (Grab $t 'static final int COST = (\w+)') $t;$costSource='COST'};$ui=$t.IndexOf('public void upgrade()');if($ui-lt 0){$ui=$t.IndexOf('public void upgrade ()')};$upgBody=if($ui-ge 0){$t.Substring($ui,[Math]::Min(1200,$t.Length-$ui))}else{''};$cards += [pscustomobject]@{id=$id;className=$f.BaseName;cost=$cost;costSource=$costSource;type=Grab $t 'CardType\.(\w+)';rarity=Grab $t 'CardRarity\.(\w+)';target=Grab $t 'CardTarget\.(\w+)';baseDamage=Resolve-Num (Grab $t 'this\.baseDamage = (\w+)') $t;baseBlock=Resolve-Num (Grab $t 'this\.baseBlock = (\w+)') $t;blockUsed=[bool]($t-match 'GainBlockAction|BlockAction|this\.block\b');baseMagic=Resolve-Num (Grab $t 'this\.baseMagicNumber = (\w+)') $t;upgDamage=Resolve-Num (Grab $t 'this\.upgradeDamage\((\w+)\)') $t;upgBlock=Resolve-Num (Grab $t 'this\.upgradeBlock\((\w+)\)') $t;upgMagic=Resolve-Num (Grab $t 'this\.upgradeMagicNumber\((\w+)\)') $t;upgCost=Resolve-Num (Grab $t 'this\.upgradeBaseCost\((\w+)\)') $t;innateOnUpg=[bool]($upgBody-match 'isInnate\s*=\s*true');exhaust=[bool]($t-match 'this\.exhaust\s*=\s*true');ethereal=[bool]($t-match 'this\.isEthereal\s*=\s*true');purgeOnUse=[bool]($t-match 'this\.purgeOnUse\s*=\s*true');selfRetain=[bool]($t-match 'this\.selfRetain\s*=\s*true');innate=[bool]($t-match 'this\.isInnate\s*=\s*true');unplayable=($cost-eq -2)}};$payload=[pscustomobject]@{generatedAt=(Get-Date).ToString('s');javaDir=$JavaDir;count=$cards.Count;cards=$cards};$outDir=Split-Path -Parent $OutFile;if($outDir -and -not(Test-Path $outDir)){New-Item -ItemType Directory -Force -Path $outDir|Out-Null};[IO.File]::WriteAllText($OutFile,($payload|ConvertTo-Json -Depth 5),$utf8NoBom);Write-Host ("t1-spec: {0} cards -> {1}" -f $cards.Count,$OutFile)
